/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as ContactRouteImport } from './routes/contact';
import { Route as ComicsRouteImport } from './routes/comics';
import { Route as AboutRouteImport } from './routes/about';
import { Route as IndexRouteImport } from './routes/index';
import { Route as ComicsSlugRouteImport } from './routes/comics.$slug';

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any);
const ComicsRoute = ComicsRouteImport.update({
  id: '/comics',
  path: '/comics',
  getParentRoute: () => rootRouteImport,
} as any);
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const ComicsSlugRoute = ComicsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ComicsRoute,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/about': typeof AboutRoute;
  '/comics': typeof ComicsRouteWithChildren;
  '/contact': typeof ContactRoute;
  '/comics/$slug': typeof ComicsSlugRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/about': typeof AboutRoute;
  '/comics': typeof ComicsRouteWithChildren;
  '/contact': typeof ContactRoute;
  '/comics/$slug': typeof ComicsSlugRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/about': typeof AboutRoute;
  '/comics': typeof ComicsRouteWithChildren;
  '/contact': typeof ContactRoute;
  '/comics/$slug': typeof ComicsSlugRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/about' | '/comics' | '/contact' | '/comics/$slug';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/about' | '/comics' | '/contact' | '/comics/$slug';
  id: '__root__' | '/' | '/about' | '/comics' | '/contact' | '/comics/$slug';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AboutRoute: typeof AboutRoute;
  ComicsRoute: typeof ComicsRouteWithChildren;
  ContactRoute: typeof ContactRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact';
      path: '/contact';
      fullPath: '/contact';
      preLoaderRoute: typeof ContactRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/comics': {
      id: '/comics';
      path: '/comics';
      fullPath: '/comics';
      preLoaderRoute: typeof ComicsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/about': {
      id: '/about';
      path: '/about';
      fullPath: '/about';
      preLoaderRoute: typeof AboutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/comics/$slug': {
      id: '/comics/$slug';
      path: '/$slug';
      fullPath: '/comics/$slug';
      preLoaderRoute: typeof ComicsSlugRouteImport;
      parentRoute: typeof ComicsRoute;
    };
  }
}

interface ComicsRouteChildren {
  ComicsSlugRoute: typeof ComicsSlugRoute;
}

const ComicsRouteChildren: ComicsRouteChildren = {
  ComicsSlugRoute: ComicsSlugRoute,
};

const ComicsRouteWithChildren = ComicsRoute._addFileChildren(ComicsRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ComicsRoute: ComicsRouteWithChildren,
  ContactRoute: ContactRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from './router.tsx';
import type { createStart } from '@tanstack/react-start';
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
